name: demo_card_codes
description: Card Codes

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:

  cloud_firestore:
  flutter_test:
    sdk: flutter
  flutter_barcode_scanner: ^1.0.2
  flutter_colorpicker: ^0.0.4
  firebase_core: ^0.5.2
  barcode: ^1.17.1
  barcode_widget: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
